# Generated by Django 3.1.6 on 2021-03-01 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_amount', models.PositiveIntegerField()),
                ('max_amount', models.PositiveIntegerField()),
                ('charges', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.PositiveIntegerField(choices=[(1, 'Fixed'), (2, 'Percent')])),
                ('commission', models.DecimalField(decimal_places=2, max_digits=10)),
                ('minimum_charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
