# Generated by Django 3.1.6 on 2021-04-13 09:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import trans.models


class Migration(migrations.Migration):

    dependencies = [
        ('trans', '0002_charges'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Account Name')),
                ('no', models.CharField(max_length=20, verbose_name='084505001336')),
                ('ifsc', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(code='nomatch', message='Length has to be 11', regex='^.{11}$')], verbose_name='IFSC Code')),
                ('branch', models.CharField(max_length=255, verbose_name='Branch Name')),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(validators=[trans.models.OnlyPast], verbose_name='Payment Date')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Request For Amount')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'IMPS'), (2, 'RTG')], verbose_name='Payment Mode')),
                ('ref', models.CharField(max_length=255, verbose_name='Bank Ref Number')),
                ('remarks', models.TextField(blank=True, null=True)),
                ('dt', models.DateTimeField(auto_now_add=True)),
                ('deposit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trans.bank', verbose_name='Deposit Bank Name')),
            ],
        ),
    ]
