# Generated by Django 3.1.6 on 2021-04-13 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trans', '0004_paymentrequest_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrequest',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Pending'), (2, 'Confirm'), (3, 'Cancel')], default=1),
        ),
        migrations.AlterField(
            model_name='bank',
            name='no',
            field=models.CharField(max_length=20, verbose_name='Account No'),
        ),
    ]
