# Generated by Django 3.1.6 on 2021-02-19 11:15

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('username', models.CharField(max_length=55, null=True, unique=True, verbose_name='Bank Id')),
                ('name', models.CharField(blank=True, max_length=125)),
                ('is_active', models.BooleanField(default=False, verbose_name='active')),
                ('is_reseller', models.BooleanField(default=False, verbose_name='Reseller')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Staff')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to=settings.AUTH_USER_MODEL)),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', users.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bal', models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='Wallet Balance')),
                ('company', models.CharField(max_length=255, verbose_name='Company Name')),
                ('address', models.TextField()),
                ('pincode', models.CharField(max_length=6, null=True, validators=[django.core.validators.RegexValidator(message='Pincode must be entered 6 digits Long.', regex='^\\+?1?\\d{6}$')])),
                ('phone', models.CharField(max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be entered 10 digits Long.', regex='^\\+?1?\\d{10}$')])),
                ('pan_no', models.CharField(max_length=10, null=True)),
                ('pan_name', models.CharField(max_length=125, verbose_name='as on Pan Card Name')),
                ('gst_no', models.CharField(max_length=15, null=True)),
                ('verify', models.BooleanField(default=False)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WalletHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prev_bal', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Previous Balace')),
                ('amount', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Amount Added')),
                ('dt', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
    ]
