# Generated by Django 3.1.6 on 2021-03-01 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_wallethistory_remarks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallethistory',
            name='profile',
        ),
        migrations.AddField(
            model_name='wallethistory',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
            preserve_default=False,
        ),
    ]
